// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/utxoswap"
)

// UtxoSwapDelete is the builder for deleting a UtxoSwap entity.
type UtxoSwapDelete struct {
	config
	hooks    []Hook
	mutation *UtxoSwapMutation
}

// Where appends a list predicates to the UtxoSwapDelete builder.
func (usd *UtxoSwapDelete) Where(ps ...predicate.UtxoSwap) *UtxoSwapDelete {
	usd.mutation.Where(ps...)
	return usd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (usd *UtxoSwapDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, usd.sqlExec, usd.mutation, usd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (usd *UtxoSwapDelete) ExecX(ctx context.Context) int {
	n, err := usd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (usd *UtxoSwapDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(utxoswap.Table, sqlgraph.NewFieldSpec(utxoswap.FieldID, field.TypeUUID))
	if ps := usd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, usd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	usd.mutation.done = true
	return affected, err
}

// UtxoSwapDeleteOne is the builder for deleting a single UtxoSwap entity.
type UtxoSwapDeleteOne struct {
	usd *UtxoSwapDelete
}

// Where appends a list predicates to the UtxoSwapDelete builder.
func (usdo *UtxoSwapDeleteOne) Where(ps ...predicate.UtxoSwap) *UtxoSwapDeleteOne {
	usdo.usd.mutation.Where(ps...)
	return usdo
}

// Exec executes the deletion query.
func (usdo *UtxoSwapDeleteOne) Exec(ctx context.Context) error {
	n, err := usdo.usd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{utxoswap.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (usdo *UtxoSwapDeleteOne) ExecX(ctx context.Context) {
	if err := usdo.Exec(ctx); err != nil {
		panic(err)
	}
}
